-- MySQL Script generated by MySQL Workbench
-- Wed Sep  6 17:41:51 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Carrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Carrito` (
  `Codigo_Car` INT NOT NULL,
  `Cantidad_Car` INT NOT NULL,
  `Total_Car` VARCHAR(45) NOT NULL,
  `Usuario_Doc_Usu` INT NOT NULL,
  PRIMARY KEY (`Codigo_Car`, `Usuario_Doc_Usu`),
  UNIQUE INDEX `Codigo_Car_UNIQUE` (`Codigo_Car` ASC),
  UNIQUE INDEX `Cantidad_Car_UNIQUE` (`Cantidad_Car` ASC),
  UNIQUE INDEX `Total_Car_UNIQUE` (`Total_Car` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `Doc_Usu` INT NOT NULL AUTO_INCREMENT,
  `Nombre_Usu` VARCHAR(45) NOT NULL,
  `Apellido_Usu` VARCHAR(45) NOT NULL,
  `Direccion_Usu` VARCHAR(45) NULL,
  `Telefono_Usu` INT NOT NULL,
  `Correo_Usu` VARCHAR(45) NOT NULL,
  `Contraseña_Usu` VARCHAR(45) NOT NULL,
  `Rol_Usu` VARCHAR(45) NOT NULL,
  `Carrito_Codigo_Car` INT NOT NULL,
  `Carrito_Usuario_Doc_Usu` INT NOT NULL,
  PRIMARY KEY (`Doc_Usu`, `Carrito_Codigo_Car`, `Carrito_Usuario_Doc_Usu`),
  UNIQUE INDEX `Telefono_Usu_UNIQUE` (`Telefono_Usu` ASC),
  UNIQUE INDEX `Correo_Usu_UNIQUE` (`Correo_Usu` ASC),
  UNIQUE INDEX `Contraseña_Usu_UNIQUE` (`Contraseña_Usu` ASC),
  INDEX `fk_Usuario_Carrito1_idx` (`Carrito_Codigo_Car` ASC, `Carrito_Usuario_Doc_Usu` ASC),
  CONSTRAINT `fk_Usuario_Carrito1`
    FOREIGN KEY (`Carrito_Codigo_Car` , `Carrito_Usuario_Doc_Usu`)
    REFERENCES `mydb`.`Carrito` (`Codigo_Car` , `Usuario_Doc_Usu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `mydb`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Categoria` (
  `Codigo_Cat` INT NOT NULL,
  `Nombre_Cat` VARCHAR(45) NULL,
  PRIMARY KEY (`Codigo_Cat`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SUB_CATEGORIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SUB_CATEGORIA` (
  `NOMBRE_SUB_CAT` VARCHAR(45) NOT NULL,
  `CODIGO_SUB_CAT` INT NOT NULL,
  `Categoria_Codigo_Cat` INT NOT NULL,
  PRIMARY KEY (`CODIGO_SUB_CAT`, `Categoria_Codigo_Cat`),
  UNIQUE INDEX `CODIGO_SUB_CATEGORIA_UNIQUE` (`CODIGO_SUB_CAT` ASC),
  UNIQUE INDEX `NOMBRE_SUB_CAT_UNIQUE` (`NOMBRE_SUB_CAT` ASC),
  INDEX `fk_SUB_CATEGORIA_Categoria1_idx` (`Categoria_Codigo_Cat` ASC),
  CONSTRAINT `fk_SUB_CATEGORIA_Categoria1`
    FOREIGN KEY (`Categoria_Codigo_Cat`)
    REFERENCES `mydb`.`Categoria` (`Codigo_Cat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Producto` (
  `Codigo_Pro` INT NOT NULL,
  `Marca_Pro` VARCHAR(45) NULL,
  `Precio_Pro` VARCHAR(45) NULL,
  `Descripcion_Pro` VARCHAR(45) NULL,
  `Nombre_Pro` VARCHAR(45) NOT NULL,
  `FechaENT_Pro` DATE NOT NULL,
  `FechaSAL_Pro` DATE NOT NULL,
  `SUB_CATEGORIA_CODIGO_SUB_CAT` INT NOT NULL,
  PRIMARY KEY (`Codigo_Pro`, `SUB_CATEGORIA_CODIGO_SUB_CAT`),
  UNIQUE INDEX `Codigo_Pro_UNIQUE` (`Codigo_Pro` ASC),
  UNIQUE INDEX `Nombre_Pro_UNIQUE` (`Nombre_Pro` ASC),
  UNIQUE INDEX `FechaENT_Pro_UNIQUE` (`FechaENT_Pro` ASC),
  UNIQUE INDEX `FechaSAL_Pro_UNIQUE` (`FechaSAL_Pro` ASC),
  INDEX `fk_Producto_SUB_CATEGORIA1_idx` (`SUB_CATEGORIA_CODIGO_SUB_CAT` ASC),
  CONSTRAINT `fk_Producto_SUB_CATEGORIA1`
    FOREIGN KEY (`SUB_CATEGORIA_CODIGO_SUB_CAT`)
    REFERENCES `mydb`.`SUB_CATEGORIA` (`CODIGO_SUB_CAT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Metodepago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Metodepago` (
  `Codigo_MDP` INT NOT NULL,
  `Numerotarjeta_MDP` INT NOT NULL,
  `Tipodepago_MDP` VARCHAR(45) NOT NULL,
  `CodigoExpiracion_MDP` INT NOT NULL,
  `FechaExpiracion_MDP` DATE NOT NULL,
  `Carrito_Codigo_Car` INT NOT NULL,
  `Carrito_Usuario_Doc_Usu` INT NOT NULL,
  PRIMARY KEY (`Codigo_MDP`, `Carrito_Codigo_Car`, `Carrito_Usuario_Doc_Usu`),
  UNIQUE INDEX `Codigo_MDP_UNIQUE` (`Codigo_MDP` ASC),
  UNIQUE INDEX `FechaExpiracion_MDP_UNIQUE` (`FechaExpiracion_MDP` ASC),
  UNIQUE INDEX `CodigoExpiracion_MDP_UNIQUE` (`CodigoExpiracion_MDP` ASC),
  UNIQUE INDEX `Numerotarjeta_MDP_UNIQUE` (`Numerotarjeta_MDP` ASC),
  INDEX `fk_Metodepago_Carrito1_idx` (`Carrito_Codigo_Car` ASC, `Carrito_Usuario_Doc_Usu` ASC),
  CONSTRAINT `fk_Metodepago_Carrito1`
    FOREIGN KEY (`Carrito_Codigo_Car` , `Carrito_Usuario_Doc_Usu`)
    REFERENCES `mydb`.`Carrito` (`Codigo_Car` , `Usuario_Doc_Usu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Factura` (
  `Codigo_Fac` INT NOT NULL,
  `FechaVenta_Fac` DATE NOT NULL,
  `Metodepago_Codigo_MDP` INT NOT NULL,
  `Metodepago_Carrito_Codigo_Car` INT NOT NULL,
  `Metodepago_Carrito_Usuario_Doc_Usu` INT NOT NULL,
  PRIMARY KEY (`Codigo_Fac`, `Metodepago_Codigo_MDP`, `Metodepago_Carrito_Codigo_Car`, `Metodepago_Carrito_Usuario_Doc_Usu`),
  UNIQUE INDEX `FechaVenta_Fac_UNIQUE` (`FechaVenta_Fac` ASC),
  INDEX `fk_Factura_Metodepago1_idx` (`Metodepago_Codigo_MDP` ASC, `Metodepago_Carrito_Codigo_Car` ASC, `Metodepago_Carrito_Usuario_Doc_Usu` ASC),
  CONSTRAINT `fk_Factura_Metodepago1`
    FOREIGN KEY (`Metodepago_Codigo_MDP` , `Metodepago_Carrito_Codigo_Car` , `Metodepago_Carrito_Usuario_Doc_Usu`)
    REFERENCES `mydb`.`Metodepago` (`Codigo_MDP` , `Carrito_Codigo_Car` , `Carrito_Usuario_Doc_Usu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Entrega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Entrega` (
  `idEntrega` INT NOT NULL,
  `Fecha` VARCHAR(45) NULL,
  `Guia` VARCHAR(45) NULL,
  `Factura_Codigo_Fac` INT NOT NULL,
  PRIMARY KEY (`idEntrega`, `Factura_Codigo_Fac`),
  INDEX `fk_Entrega_Factura1_idx` (`Factura_Codigo_Fac` ASC),
  CONSTRAINT `fk_Entrega_Factura1`
    FOREIGN KEY (`Factura_Codigo_Fac`)
    REFERENCES `mydb`.`Factura` (`Codigo_Fac`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario_has_Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario_has_Producto` (
  `Usuario_Doc_Usu` INT NOT NULL,
  `Producto_Codigo_Pro` INT NOT NULL,
  PRIMARY KEY (`Usuario_Doc_Usu`, `Producto_Codigo_Pro`),
  INDEX `fk_Usuario_has_Producto_Producto1_idx` (`Producto_Codigo_Pro` ASC),
  INDEX `fk_Usuario_has_Producto_Usuario_idx` (`Usuario_Doc_Usu` ASC),
  CONSTRAINT `fk_Usuario_has_Producto_Usuario`
    FOREIGN KEY (`Usuario_Doc_Usu`)
    REFERENCES `mydb`.`Usuario` (`Doc_Usu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_Producto_Producto1`
    FOREIGN KEY (`Producto_Codigo_Pro`)
    REFERENCES `mydb`.`Producto` (`Codigo_Pro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
